FirewallDnsName = "pan-fw"
FirewallVmName = "vvPANW"
FirewallVmSize = "Standard_D3_v2"
FromGatewayLogin = "0.0.0.0/0"
StorageAccountName = "vvstg11"
WebServerDnsName = "pan-web"
location = "westus2"
resource_group_name = "vvrg12"
